data_config:
  TRAIN_DIR: "data/raw/braintumor/Training"
  TEST_DIR: "data/raw/braintumor/Testing"
  VALIDATION_SPLIT: 0.2
  IMG_SIZE: [224, 224]
  BATCH_SIZE: 32
  SEED: 42

model_config:
  optimizer: "adam"
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]
  epochs: 1

optimizer_config:
  learning_rate: 0.0001

callbacks:
  early_stopping:
    monitor: "val_loss"
    patience: 3
    restore_best_weights: True

training:
  use_class_weights: True
  shuffle: True


transfer_learning:
  freeze_base_model: True
  unfreeze_last_n_layers: 0

augmentation:
  enabled: True
  horizontal_flip: True
  rotation: 0.1
  zoom: 0.1
